language: python
python:
  - "3.5"

env:
  global:
    # GITHUB_TOKEN=...
    - secure: "NVj+dKlTlOySMVqMdotAkoQkys1tnLo6GBNwZ6NRcaKRtIq1tF0edRUey3EWHVsNueHDzZzkiXZeeGdskQ0IoUm1qMEZ1pf6GR8iLkraZnUdqqYvSO1HFY96GzpkZ2pGDzj8cU2MQIQf2G8rh+SJyoVCD/VeKc62NlAKxXiLXgbFby+80lmaLkluGlsxOurKXhcBYRZbH5Z51vC4Dz51SQozFy2+Ld4QpEAqoFaY0810XZUcNtjEKECsiFApyqU+SeHbw8lzid0ryOPmZBi/voyq6N0L3ILy9m8CoormIP+5M0SLuspWy8OmFMS1YXotk/7usu/fRwOQwevT5p+SkQajaMNQwXvwy33i3nR6fHBN+r6lmiHtI4soPWAxJ74ozfsEO5sx4frn3xE3ulQn/mRzl9obAKjzr/WrudmlN6v5qCh4x1gscMAPDJ3dSafuVVuehsh3KEQNROgoOr85S9qTx7jhhPwR6ofl7zG7R+JfTBn6mqX4g4h7iz5aC/QwenHPyKp8ramuf7mYaJrMHOv1HalsgYkCKwDpI4k0Y27UnhcDR/lW99BXCMP2A5k1ksBN0mrzmO+Mk0bUHUKUjoR1Ax0BYRVAdyGkepNjHpCyRMsWzwzyO1hBHARbg0iE+RFieCSAKbXtKn+qUcwf1mE8ETWdXkGuoqUegzwuL3E="
    # DEPLOY_PASS=....
    - secure: "DFcxHEAcLfy8BPlJX8KubAjpyAUsANmUigRXLxliPqFQHKK7EcG6wa+GiI/JrAXNgnKD2l/9FGQJ0B1/CCvYvysRU77OYG4Z80FwWsiLvDTp4w+v7AifGKUN/NX96ecvXOJmiJJlIZ0TtA0aUB/VJG4LI/UGC62//k7wJXZHUIrAPF8aHHcOgcs0VwQPPnxgpJrALmkWqcmN5SBW5v8Li3sbT4iquEiM33GLb0JkJmu9gBNWhx1jPI69Bp0B3e8GJH2oxrU6XfTmDMDAJVTblPgJRsIOyU4r+sSA/aCq0yAVCKm9ZrONwdpeyri4QlovzqxyXeLVBvJj6SUuBRVWecmH3OonFzC/cefzOfZ6Qt4XNvOEK6ar/XIa6D1f8Sp7uuerFglDZXWkbxf+OXfHnp3JpTpZQFNs+/CS7PiX4hLm/em2xZgPPQDfPbF0wpkZ793DlK4o8NZo6ts2hZp1MPKSHkDgNVQo3gd8J93kW9UxSfToZc8epbJVvBFdKrirov7uTH1qm7DCXnycXAMYIKMHuLq9mLVUcDmUftdLSU7sT3hlo6pqc7kpc3QcRCIq69ZCFKokWzk7Jx2FCSTObihYESHDf9vRPy6xVPMNTpj44T633tbVnZe3eB8lW3qn8VsdOfNFfSP2IAaCU0PqpLkG6guaNm0cxTPJGMJGJlE="
    - VERSION=v1.0.$TRAVIS_BUILD_NUMBER
    - OWNER=palette-software
    - PACKAGE=insight-services-status
    - DEPLOY_HOST=rpm.palette-software.com
    - DEPLOY_PATH=/var/palette-rpm-repo
    - DEPLOY_USER=palette-rpm

# install the RPM package
addons:
  apt:
    packages:
      - rpm
      # To deploy the rpms, we need to ssh into places, and we dont want to store keys for now
      - sshpass

# command to install dependencies
install: "pip install -r requirements.txt"

script:
  # Create the zip file for github upload
  - export PCKG_DIR=`pwd`
  - export PCKG_FILE=$PACKAGE-$VERSION-python$TRAVIS_PYTHON_VERSION.zip
  - zip -r $PCKG_FILE $PCKG_DIR -x \*.git\* -x *\.travis.yml\*

  # Run tests
  - pip install assertpy
  - python -m unittest

  # Build rpm package
  - ./create_rpm.sh

deploy:
  provider: script
  script: "./deploy.sh"
  skip_cleanup: true
  on:
    branch: master
    tags: false

notifications:
  email: false
