language: python
python:
  #- "2.7"
  - "3.5"

env:
  global:
    secure: "NVj+dKlTlOySMVqMdotAkoQkys1tnLo6GBNwZ6NRcaKRtIq1tF0edRUey3EWHVsNueHDzZzkiXZeeGdskQ0IoUm1qMEZ1pf6GR8iLkraZnUdqqYvSO1HFY96GzpkZ2pGDzj8cU2MQIQf2G8rh+SJyoVCD/VeKc62NlAKxXiLXgbFby+80lmaLkluGlsxOurKXhcBYRZbH5Z51vC4Dz51SQozFy2+Ld4QpEAqoFaY0810XZUcNtjEKECsiFApyqU+SeHbw8lzid0ryOPmZBi/voyq6N0L3ILy9m8CoormIP+5M0SLuspWy8OmFMS1YXotk/7usu/fRwOQwevT5p+SkQajaMNQwXvwy33i3nR6fHBN+r6lmiHtI4soPWAxJ74ozfsEO5sx4frn3xE3ulQn/mRzl9obAKjzr/WrudmlN6v5qCh4x1gscMAPDJ3dSafuVVuehsh3KEQNROgoOr85S9qTx7jhhPwR6ofl7zG7R+JfTBn6mqX4g4h7iz5aC/QwenHPyKp8ramuf7mYaJrMHOv1HalsgYkCKwDpI4k0Y27UnhcDR/lW99BXCMP2A5k1ksBN0mrzmO+Mk0bUHUKUjoR1Ax0BYRVAdyGkepNjHpCyRMsWzwzyO1hBHARbg0iE+RFieCSAKbXtKn+qUcwf1mE8ETWdXkGuoqUegzwuL3E="
    - PRODUCT_VERSION=v1.0.$TRAVIS_BUILD_NUMBER
    - OWNER=palette-software
    - PACKAGE=insight-services-status

# command to install dependencies
install: "pip install -r requirements.txt"

# command to run tests
script: echo "No Tests right now :("

before_deploy:
  - export PCKG_DIR=`pwd`
  - export PCKG_FILE=$PACKAGE-$PRODUCT_VERSION-python$TRAVIS_PYTHON_VERSION.zip
  - zip -r $PCKG_FILE $PCKG_DIR -x \*.git\* -x *\.travis.yml\*

deploy:
  skip_cleanup: true
  provider: script
  # Only deploy from the master branch (and if we don't have a tag specified, because they are auto-committed)
  script: $TRAVIS_BUILD_DIR/release-to-github.sh
  on:
    branch: master
    tags: false

notifications:
  email: false
